security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io.pivotal.demo.bosh: DEBUG

bosh:
  director: https://${bosh.director.ip}:25555/
  oauth:
    clientID: ${bosh.director.clientId}
    clientSecret: ${bosh.director.secret}
    accessTokenUri: https://${bosh.director.ip}:8443/oauth/token
  ssh:
    enabled: true
    cpi: gcp
    gcp:
      project: fe-azwickey

