security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging:
  level:
    io.pivotal.demo.bosh: DEBUG

bosh:
  director: https://${bosh.director.ip:127.0.0.1}:25555/
  oauth:
    clientID: ${bosh.director.clientId:admin}
    clientSecret: ${bosh.director.secret:xxxxx}
    accessTokenUri: https://${bosh.director.ip:127.0.0.1}:8443/oauth/token
